#!/bin/bash 

IFLAG=/etc/columnstore/container-initialized
LOG_PREFIX=/var/log/mariadb/columnstore
MCS_INSTALL_BIN=/usr/bin

# Intialize Container If Necessary
if [ ! -e $IFLAG ]; then
  $MCS_INSTALL_BIN/columnstore-init &> $LOG_PREFIX/columnstore-init.log
fi

echo Starting...

touch $LOG_PREFIX/cmapi_server.log && chmod 666 $LOG_PREFIX/cmapi_server.log
PYTHONPATH=/opt/cmapi/deps /opt/cmapi/python/bin/python3 -m /opt/cmapi/cmapi_server &> $LOG_PREFIX/cmapi_server.log &
echo CMAPI PID = $!

/usr/share/mysql/mysql.server start
exit 0
