#!/bin/bash 

LOG_PREFIX=/var/log/mariadb/columnstore
MCS_INSTALL_BIN=/usr/bin

echo Starting...

touch $LOG_PREFIX/cmapi_server.log && chmod 666 $LOG_PREFIX/cmapi_server.log
PYTHONPATH=/opt/cmapi/deps /opt/cmapi/python/bin/python3 -m /opt/cmapi/cmapi_server &> $LOG_PREFIX/cmapi_server.log &
echo CMAPI PID = $!

/usr/share/mysql/mysql.server start
exit 0
